# Generated by Django 4.1 on 2022-08-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
